// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: protobufDataPlane/dataPlane.proto

package razpravljalnica

import (
	protobufStorage "api/razpravljalnica/protobufStorage"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	SequenceNumber int64                    `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Op             protobufStorage.OpType   `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`
	Message        *protobufStorage.Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_protobufDataPlane_dataPlane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufDataPlane_dataPlane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_protobufDataPlane_dataPlane_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *UpdateRequest) GetOp() protobufStorage.OpType {
	if x != nil {
		return x.Op
	}
	return protobufStorage.OpType(0)
}

func (x *UpdateRequest) GetMessage() *protobufStorage.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type AcknowledgeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcknowledgeResponse) Reset() {
	*x = AcknowledgeResponse{}
	mi := &file_protobufDataPlane_dataPlane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeResponse) ProtoMessage() {}

func (x *AcknowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufDataPlane_dataPlane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) {
	return file_protobufDataPlane_dataPlane_proto_rawDescGZIP(), []int{1}
}

func (x *AcknowledgeResponse) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AcknowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protobufDataPlane_dataPlane_proto protoreflect.FileDescriptor

const file_protobufDataPlane_dataPlane_proto_rawDesc = "" +
	"\n" +
	"!protobufDataPlane/dataPlane.proto\x12\x0frazpravljalnica\x1a%protobufStorage/protobufStorage.proto\"\x95\x01\n" +
	"\rUpdateRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\"X\n" +
	"\x13AcknowledgeResponse\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2b\n" +
	"\tDataPlane\x12U\n" +
	"\rForwardUpdate\x12\x1e.razpravljalnica.UpdateRequest\x1a$.razpravljalnica.AcknowledgeResponseB7Z5api/razpravljalnica/protobufDataPlane;razpravljalnicab\x06proto3"

var (
	file_protobufDataPlane_dataPlane_proto_rawDescOnce sync.Once
	file_protobufDataPlane_dataPlane_proto_rawDescData []byte
)

func file_protobufDataPlane_dataPlane_proto_rawDescGZIP() []byte {
	file_protobufDataPlane_dataPlane_proto_rawDescOnce.Do(func() {
		file_protobufDataPlane_dataPlane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufDataPlane_dataPlane_proto_rawDesc), len(file_protobufDataPlane_dataPlane_proto_rawDesc)))
	})
	return file_protobufDataPlane_dataPlane_proto_rawDescData
}

var file_protobufDataPlane_dataPlane_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufDataPlane_dataPlane_proto_goTypes = []any{
	(*UpdateRequest)(nil),           // 0: razpravljalnica.UpdateRequest
	(*AcknowledgeResponse)(nil),     // 1: razpravljalnica.AcknowledgeResponse
	(protobufStorage.OpType)(0),     // 2: razpravljalnica.OpType
	(*protobufStorage.Message)(nil), // 3: razpravljalnica.Message
}
var file_protobufDataPlane_dataPlane_proto_depIdxs = []int32{
	2, // 0: razpravljalnica.UpdateRequest.op:type_name -> razpravljalnica.OpType
	3, // 1: razpravljalnica.UpdateRequest.message:type_name -> razpravljalnica.Message
	0, // 2: razpravljalnica.DataPlane.ForwardUpdate:input_type -> razpravljalnica.UpdateRequest
	1, // 3: razpravljalnica.DataPlane.ForwardUpdate:output_type -> razpravljalnica.AcknowledgeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobufDataPlane_dataPlane_proto_init() }
func file_protobufDataPlane_dataPlane_proto_init() {
	if File_protobufDataPlane_dataPlane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufDataPlane_dataPlane_proto_rawDesc), len(file_protobufDataPlane_dataPlane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufDataPlane_dataPlane_proto_goTypes,
		DependencyIndexes: file_protobufDataPlane_dataPlane_proto_depIdxs,
		MessageInfos:      file_protobufDataPlane_dataPlane_proto_msgTypes,
	}.Build()
	File_protobufDataPlane_dataPlane_proto = out.File
	file_protobufDataPlane_dataPlane_proto_goTypes = nil
	file_protobufDataPlane_dataPlane_proto_depIdxs = nil
}
