// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: controlPlane.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ClientAddress  string                 `protobuf:"bytes,3,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	ControlAddress string                 `protobuf:"bytes,4,opt,name=control_address,json=controlAddress,proto3" json:"control_address,omitempty"`
	DataAddress    string                 `protobuf:"bytes,5,opt,name=data_address,json=dataAddress,proto3" json:"data_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_controlPlane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlPlane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlPlane_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterNodeRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterNodeRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetControlAddress() string {
	if x != nil {
		return x.ControlAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetDataAddress() string {
	if x != nil {
		return x.DataAddress
	}
	return ""
}

type RegisterNodeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssignedPosition int64                  `protobuf:"varint,1,opt,name=assigned_position,json=assignedPosition,proto3" json:"assigned_position,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_controlPlane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlPlane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_controlPlane_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetAssignedPosition() int64 {
	if x != nil {
		return x.AssignedPosition
	}
	return 0
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	Sub           *NodeInfo              `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_controlPlane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlPlane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_controlPlane_proto_rawDescGZIP(), []int{2}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *GetClusterStateResponse) GetSub() *NodeInfo {
	if x != nil {
		return x.Sub
	}
	return nil
}

type GetNextNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextNodeRequest) Reset() {
	*x = GetNextNodeRequest{}
	mi := &file_controlPlane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextNodeRequest) ProtoMessage() {}

func (x *GetNextNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlPlane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNextNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlPlane_proto_rawDescGZIP(), []int{3}
}

func (x *GetNextNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_controlPlane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controlPlane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_controlPlane_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_controlPlane_proto protoreflect.FileDescriptor

const file_controlPlane_proto_rawDesc = "" +
	"\n" +
	"\x12controlPlane.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\"\xb5\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12%\n" +
	"\x0eclient_address\x18\x03 \x01(\tR\rclientAddress\x12'\n" +
	"\x0fcontrol_address\x18\x04 \x01(\tR\x0econtrolAddress\x12!\n" +
	"\fdata_address\x18\x05 \x01(\tR\vdataAddress\"]\n" +
	"\x14RegisterNodeResponse\x12+\n" +
	"\x11assigned_position\x18\x01 \x01(\x03R\x10assignedPosition\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xa4\x01\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\x12+\n" +
	"\x03sub\x18\x03 \x01(\v2\x19.razpravljalnica.NodeInfoR\x03sub\"-\n" +
	"\x12GetNextNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\x8f\x02\n" +
	"\fControlPlane\x12[\n" +
	"\fRegisterNode\x12$.razpravljalnica.RegisterNodeRequest\x1a%.razpravljalnica.RegisterNodeResponse\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12M\n" +
	"\vGetNextNode\x12#.razpravljalnica.GetNextNodeRequest\x1a\x19.razpravljalnica.NodeInfoB\x12Z\x10/razpravljalnicab\x06proto3"

var (
	file_controlPlane_proto_rawDescOnce sync.Once
	file_controlPlane_proto_rawDescData []byte
)

func file_controlPlane_proto_rawDescGZIP() []byte {
	file_controlPlane_proto_rawDescOnce.Do(func() {
		file_controlPlane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlPlane_proto_rawDesc), len(file_controlPlane_proto_rawDesc)))
	})
	return file_controlPlane_proto_rawDescData
}

var file_controlPlane_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controlPlane_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),     // 0: razpravljalnica.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),    // 1: razpravljalnica.RegisterNodeResponse
	(*GetClusterStateResponse)(nil), // 2: razpravljalnica.GetClusterStateResponse
	(*GetNextNodeRequest)(nil),      // 3: razpravljalnica.GetNextNodeRequest
	(*NodeInfo)(nil),                // 4: razpravljalnica.NodeInfo
	(*emptypb.Empty)(nil),           // 5: google.protobuf.Empty
}
var file_controlPlane_proto_depIdxs = []int32{
	4, // 0: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	4, // 1: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	4, // 2: razpravljalnica.GetClusterStateResponse.sub:type_name -> razpravljalnica.NodeInfo
	0, // 3: razpravljalnica.ControlPlane.RegisterNode:input_type -> razpravljalnica.RegisterNodeRequest
	5, // 4: razpravljalnica.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	3, // 5: razpravljalnica.ControlPlane.GetNextNode:input_type -> razpravljalnica.GetNextNodeRequest
	1, // 6: razpravljalnica.ControlPlane.RegisterNode:output_type -> razpravljalnica.RegisterNodeResponse
	2, // 7: razpravljalnica.ControlPlane.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	4, // 8: razpravljalnica.ControlPlane.GetNextNode:output_type -> razpravljalnica.NodeInfo
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_controlPlane_proto_init() }
func file_controlPlane_proto_init() {
	if File_controlPlane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlPlane_proto_rawDesc), len(file_controlPlane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlPlane_proto_goTypes,
		DependencyIndexes: file_controlPlane_proto_depIdxs,
		MessageInfos:      file_controlPlane_proto_msgTypes,
	}.Build()
	File_controlPlane_proto = out.File
	file_controlPlane_proto_goTypes = nil
	file_controlPlane_proto_depIdxs = nil
}
